numero = int(input('Me diga um número:'))
n = str(numero)
print(f'Analisando o número que você disse,no caso o {numero}...')
print(f'Unidade: {n[3]}')
print(f'Dezena: {n[2]}')
print(f'Centena: {n[1]}')
print(f'Milhar: {n[0]}')
