nome =str(input('Digite seu nome completo: ')).title()
lista = nome.split(' ')
print(f'Prazer em conhecer você! {lista [0]} ')
print(f'seu primeiro nome é {lista [0]} ')
print(f"seu ultimo nome é {lista [-1]}")
